// <auto-generated />
using System;
using EMS.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.DAL.Migrations
{
    [DbContext(typeof(EMSContext))]
    partial class EMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.DAL.Models.EventDetails", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EventId");

                    b.ToTable("EventDetails");

                    b.HasData(
                        new
                        {
                            EventId = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Join us for an exciting summit on AI and Machine Learning innovations. Learn from industry experts about the latest trends and technologies.",
                            EventCategory = "Tech & Innovations",
                            EventDate = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "AI & Machine Learning Summit",
                            Location = "Virtual",
                            MaxParticipants = 500,
                            Status = "Active"
                        },
                        new
                        {
                            EventId = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Discover how digital transformation is revolutionising the manufacturing industry. Explore IoT, Industry 4.0, and automation technologies.",
                            EventCategory = "Industrial Events",
                            EventDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Digital Transformation in Manufacturing",
                            Location = "Hybrid (In-person + Virtual)",
                            MaxParticipants = 300,
                            Status = "Active"
                        },
                        new
                        {
                            EventId = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Enhance your leadership skills with industry experts. Learn strategies for team building, decision making, and organisational management.",
                            EventCategory = "Leadership",
                            EventDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Leadership Excellence Workshop",
                            Location = "Convention Center, New York",
                            MaxParticipants = 200,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("EMS.DAL.Models.ParticipantEventDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Feedback")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAttended")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ParticipantEmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ParticipantEmailId", "EventId")
                        .IsUnique();

                    b.ToTable("ParticipantEventDetails");
                });

            modelBuilder.Entity("EMS.DAL.Models.SessionInfo", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("SessionEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SessionStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SessionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SpeakerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SessionId");

                    b.HasIndex("EventId");

                    b.HasIndex("SpeakerId");

                    b.ToTable("SessionInfo");

                    b.HasData(
                        new
                        {
                            SessionId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Capacity = 100,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An introductory session on artificial intelligence concepts and applications.",
                            EventId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Location = "Virtual - Zoom",
                            SessionEnd = new DateTime(2026, 5, 17, 10, 30, 0, 0, DateTimeKind.Utc),
                            SessionStart = new DateTime(2026, 5, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            SessionTitle = "Introduction to AI",
                            SessionUrl = "https://example.com/session1",
                            SpeakerId = new Guid("33333333-3333-3333-3333-333333333301"),
                            Status = "Scheduled"
                        },
                        new
                        {
                            SessionId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Capacity = 80,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Explore Internet of Things applications in modern manufacturing.",
                            EventId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Location = "Convention Center, New York",
                            SessionEnd = new DateTime(2026, 5, 22, 11, 30, 0, 0, DateTimeKind.Utc),
                            SessionStart = new DateTime(2026, 5, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            SessionTitle = "IoT in Manufacturing",
                            SessionUrl = "https://example.com/session2",
                            SpeakerId = new Guid("33333333-3333-3333-3333-333333333302"),
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("EMS.DAL.Models.SpeakersDetails", b =>
                {
                    b.Property<Guid>("SpeakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeakerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SpeakerId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("SpeakersDetails");

                    b.HasData(
                        new
                        {
                            SpeakerId = new Guid("33333333-3333-3333-3333-333333333301"),
                            Bio = "Expert in artificial intelligence and machine learning with 10+ years of experience.",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Designation = "AI Research Lead",
                            Email = "sarah.johnson@example.com",
                            IsActive = true,
                            LinkedInUrl = "https://linkedin.com/in/sarahjohnson",
                            Organization = "Tech Innovations Inc.",
                            PhoneNumber = "+1-555-0101",
                            SpeakerName = "Dr. Sarah Johnson"
                        },
                        new
                        {
                            SpeakerId = new Guid("33333333-3333-3333-3333-333333333302"),
                            Bio = "Specialised in IoT and Industry 4.0 with extensive manufacturing background.",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Designation = "Manufacturing Engineer",
                            Email = "david.kumar@example.com",
                            IsActive = true,
                            LinkedInUrl = "https://linkedin.com/in/davidkumar",
                            Organization = "Industrial Solutions Ltd.",
                            PhoneNumber = "+1-555-0102",
                            SpeakerName = "Mr. David Kumar"
                        });
                });

            modelBuilder.Entity("EMS.DAL.Models.UserInfo", b =>
                {
                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmailId");

                    b.ToTable("UserInfo");

                    b.HasData(
                        new
                        {
                            EmailId = "admin@upgrad.com",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Password = "Admin@321",
                            Role = "Admin",
                            UserName = "Admin User"
                        });
                });

            modelBuilder.Entity("EMS.DAL.Models.ParticipantEventDetails", b =>
                {
                    b.HasOne("EMS.DAL.Models.EventDetails", "Event")
                        .WithMany("ParticipantRegistrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.DAL.Models.UserInfo", "User")
                        .WithMany("ParticipantEvents")
                        .HasForeignKey("ParticipantEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EMS.DAL.Models.SessionInfo", b =>
                {
                    b.HasOne("EMS.DAL.Models.EventDetails", "Event")
                        .WithMany("Sessions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.DAL.Models.SpeakersDetails", "Speaker")
                        .WithMany("Sessions")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("EMS.DAL.Models.EventDetails", b =>
                {
                    b.Navigation("ParticipantRegistrations");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("EMS.DAL.Models.SpeakersDetails", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("EMS.DAL.Models.UserInfo", b =>
                {
                    b.Navigation("ParticipantEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
